#!/usr/bin/env bash

cd "$( dirname "${BASH_SOURCE[0]}" )"
cd ../

GEOWAVE_DEMO_APP=mil.nga.giat.geowave.examples.accumulo.app.GeoWaveDemoApp
GEOWAVE_CLI_MAIN=mil.nga.giat.geowave.core.cli.GeoWaveMain
PID_PATH_NAME=$(pwd)/test/.geowave-pid

ZOOKEEPER_URL=localhost:2181
INSTANCE_NAME=geowave
USERNAME=root
PASSWORD=password
TABLE_NAMESPACE=mapnik
ADAPTER_TYPE=geotools-vector
ADAPTER_ID=world_merc

SHAPEFILE=$(pwd)/test/data/shp/world_merc.shp

geowave_start() {
  if [ ! -f $PID_PATH_NAME ]; then
    echo "Starting GeoWave ..."
    nohup java -Dinteractive=false -cp $GEOWAVE_EXAMPLE_JAR:$GEOWAVE_FORMAT_VECTOR_JAR:$GEOWAVE_RUNTIME_JAR:$GEOWAVE_TOOLS_JAR $GEOWAVE_DEMO_APP /tmp 2>> /dev/null >> /dev/null &
    echo $! > $PID_PATH_NAME
    sleep 5
    echo "GeoWave started ..."
  else
    echo "GeoWave is already running ..."
  fi
}

geowave_ingest() {
  if [ -f $PID_PATH_NAME ]; then
    java -cp $GEOWAVE_EXAMPLE_JAR:$GEOWAVE_FORMAT_VECTOR_JAR:$GEOWAVE_RUNTIME_JAR:$GEOWAVE_TOOLS_JAR $GEOWAVE_CLI_MAIN config addindex -t spatial spatial
    java -cp $GEOWAVE_EXAMPLE_JAR:$GEOWAVE_FORMAT_VECTOR_JAR:$GEOWAVE_RUNTIME_JAR:$GEOWAVE_TOOLS_JAR $GEOWAVE_CLI_MAIN config addstore -t accumulo accumulo --gwNamespace $TABLE_NAMESPACE -z $ZOOKEEPER_URL -u $USERNAME -p $PASSWORD -i $INSTANCE_NAME
    java -cp $GEOWAVE_EXAMPLE_JAR:$GEOWAVE_FORMAT_VECTOR_JAR:$GEOWAVE_RUNTIME_JAR:$GEOWAVE_TOOLS_JAR $GEOWAVE_CLI_MAIN ingest localToGW -f $ADAPTER_TYPE $SHAPEFILE accumulo spatial
  else
    echo "GeoWave is not running ..."
  fi
}

geowave_stop() {
  if [ -f $PID_PATH_NAME ]; then
    PID=$(cat $PID_PATH_NAME);
    echo "GeoWave stopping ..."
    kill $PID;
    echo "GeoWave stopped ..."
    rm $PID_PATH_NAME
  else
    echo "GeoWave is not running ..."
  fi
}

$@
